---
all:
  children:
    # ---------------------------------------------------------
    # Environment Groups (grouping by tier)
    # ---------------------------------------------------------
    test:
      hosts:
        web-test-01.example.com:
        db-test-01.example.com:
    prod:
      hosts:
        web-prod-01.example.com:
        web-prod-02.example.com:
        db-prod-01.example.com:

    # ---------------------------------------------------------
    # Role Groups (grouping by function)
    # ---------------------------------------------------------
    web:
      hosts:
        web-test-01.example.com:
        web-prod-01.example.com:
        web-prod-02.example.com:
    db:
      hosts:
        db-test-01.example.com:
        db-prod-01.example.com: